### ISSUE TITLE
協力の申し入れ

### ISSUE THREAD

**Issue by KeenS** [hazama-yuinyan/book#1]
こんにちは。 https://github.com/rust-lang-ja の管理をしているκeenです。TRPLの2nd editionを翻訳されているようなので何か協力できないかと思いましてissue立てました。[1st editionの訳](https://github.com/rust-lang-ja/the-rust-programming-language-ja)はありますが、手が足りなくて最新版に追従できずにいたので2ndの翻訳プロジェクトはとてもありがたいです。

1stを翻訳するにあたって必要だったものがこちらで何か役に立てないかと思っています。例えば[対訳表](https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/TranslationTable.md)を整備していたりします。訳に悩まないという意味でもユーザを混乱させないという意味でも利用して頂けたらと思います。
あるいはレビューをしてほしいなら @ で呼んでいただけたらレビーはできるかと思います（忙しいと少し時間がかかってしまうかもしれませんが）。

また、このドキュメントをrust-lang-jaに移したいのなら招待します。現状、それぞれ独立して管理されているので移管しても自分のペース、方針で翻訳できます。

何かお役に立てそうであればご連絡下さい。

**Comment by hazama-yuinyan** [comment]
まず始めに、ご協力の申し出、ありがとうございます。大変ありがたいです。
対訳表、確認させていただきましたが、第3章まで翻訳し終えて、一部倣っていない箇所があったので、
修正が必要かもしれないと感じております。
ただ、私の個人的な方針として、わかりやすい和訳を心がけることを目標にしておりますので、同じ単語に対する訳語が変わってしまうことでどれほど読者を混乱させてしまうのかついて、定量的に評価できる資料があるとありがたいかなとは存じます。

ご協力いただけるのであれば、公式リポジトリのProjectsページでFrozenに入ったものから順に翻訳していっているので、読みやすさ(個人的に難しい漢字を使いすぎてしまう傾向があるので、第三者がみて理解しやすいかどうか)やもちろん誤字などがないかどうか、スタイルの統一性(ですます調で堅苦しすぎない文章を目指しているので、その統一性)などを精読していただけると、非常に助かります。

ドキュメントをrust-lang-jaに移すかどうかについては、先方でも翻訳についてツールの開発が進まないとサポートしづらい状況にあるようで、現状当方のリポジトリへのリンクを張るだけで解決するとのことなので、先方を混乱させないためにも、当分は無しの方向でお願いしたいところでございます。

以上で、回答になっているでしょうか。ご協力者が存在することは、私としても大変ありがたいことですので、是非とも、一緒にRustの日本普及に一役買えるよう、頑張っていきたい所存でございます。

**Comment by KeenS** [comment]
> 訳語が変わってしまうことでどれほど読者を混乱させてしまうのかついて、定量的に評価できる資料があるとありがたいかなとは存じます。

特にはないです。感覚的なものですね。だた、テクニカルタームについては訳が一定していないと正確に伝わらないかなと思います（個人の感想です。

> 精読していただけると、非常に助かります。

了解しました。書式などは1st editionのときに[整理した](https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/CONTRIBUTING.md#%E6%9B%B8%E5%BC%8F%E9%A1%9E)のでそれを見ながらやろうかと思います。
ところで原文を削除して訳されているようですが、精読する際に原文がないと手を入れづらいのでコメントか何かで残して頂けるとありがたいです （[参考](https://raw.githubusercontent.com/rust-lang-ja/the-rust-programming-language-ja/master/1.6/ja/book/primitive-types.md)）。あとはプルリク駆動だとdiffが見易いので作業しやすくなります。

> ドキュメントをrust-lang-jaに移すかどうかについては（中略）当分は無しの方向でお願いしたいところでございます。

了解しました

2ndが正式なドキュメントになったら和訳も主にこちらが参照されることになると思うのでコミュニティに後ろ指を指されないクオリティにしましょう。

**Comment by hazama-yuinyan** [comment]
> テクニカルタームについては訳が一定していないと正確に伝わらないかなと思います

対訳表、確認させていただきました。なるべく、善処はしますが、その訳にした意図が読めず、ご意向に沿えない可能性があります。ご了承ください。
> 精読する際に原文がないと手を入れづらいのでコメントか何かで残して頂けるとありがたいです

とのことで、メンテナンスも大変になりそうなので、既存の章にも、コメントで原文を追記しておきました。ご活用ください。
> あとはプルリク駆動だとdiffが見易いので作業しやすくなります。

プルリク駆動ということは、Collaboratorsに招待すればよろしいのでしょうか？なにぶん、Githubでチーム開発プロジェクトを管理するのは初めてなので、ご容赦いただければ幸いです。

**Comment by KeenS** [comment]
> プルリク駆動ということは、Collaboratorsに招待すればよろしいのでしょうか？なにぶん、Githubでチーム開発プロジェクトを管理するのは初めてなので、ご容赦いただければ幸いです。

レビューだけなら別にCollaboratorでなくても大丈夫だと思います。Collaboratorにして頂いても構いませんが。

**Comment by hazama-yuinyan** [comment]
承知いたしました。では、ひとまず、Collaboratorsには追加なしで運用いたします。

> 書式などは1st editionのときに整理したのでそれを見ながらやろうかと思います。

こちらも確認させていただきました。すでに翻訳済みの箇所は、こちらの書式に沿っていない箇所が多そうなので、精読いただいた際には、そちらもご確認、ご指摘いただけると幸いです。
> 英文をコメントアウトして、その直下に（空行を空けずに）和訳を書く

これについては、mdbookというツールの仕様上、コメント後に1行、空行を空けないと正しくパースしてくれないようなので、目をつぶっていただけると助かります。
今後とも、よろしくお願いいたします。

**Comment by KeenS** [comment]
> mdbookというツールの仕様上、コメント後に1行、空行を空けないと正しくパースしてくれないようなので、

了解しました。いくつかポリシーがあるようですし1stのCONTRIBUTINGをフォークして書き直した方がいいかもしれませんね。

今月は手が空かないのですぐにという訳にはいかないと思いますがちょっとずつお手伝いしていきます。

**Comment by hazama-yuinyan** [comment]
> 今月は手が空かないのですぐにという訳にはいかないと思いますがちょっとずつお手伝いしていきます。

承知しました。ゆっくりで構わない上、レビューはなかなか骨の折れる作業ですから、マイペースで作業していただいて構いません。
よろしくお願いいたします。

**Comment by KeenS** [comment]
こちら、閉じておきますね。
