### ISSUE TITLE
2章のマージについて

### ISSUE THREAD

**Issue by hazama-yuinyan** [hazama-yuinyan/book#11]
第2章のマージについて、議論が必要そうな文章があったため、こちらで議論の上、マージするか決定したいと考えております。 #2 でコメントを残していますので、本文のコメントと合わせて議論させてください。叙述用法の形容詞を和訳として認めるかどうかは、議論の上、README.mdに記載しようと思います。 @KeenS さん、よろしくお願いいたいします

**Comment by KeenS** [comment]
お返事遅くなりました。 どちらも鵜呑みにできる情報ではないですがネット上で見つけた[形容詞の二つの統語機能](https://www.gcoe.lit.nagoya-u.ac.jp/result/pdf/3-2_%e9%87%91%e9%8a%80%e7%8f%a0.pdf)やWikipediaの[形容詞句](https://ja.wikipedia.org/wiki/%E5%BD%A2%E5%AE%B9%E8%A9%9E%E5%8F%A5)のページを見るに、特に訳文のために叙述用法を導入したような書き方はおらず、英語のadjectiveと完全に用法が一致するわけではない(強いて言うなら日本語の形容詞の方が単独で叙述文を作れると書いてある)くらいしか書かれていないようです。

私としては現代日本語で意味が通じるなら別に問題ないと思います。つきつめるとやまとことば以外使わないとかになりかねないので。

**Comment by hazama-yuinyan** [comment]
承知しました。では、認めることにしましょうか。

> 一つマージする際に忘れてしまっていましたが、対訳表にもあるarmの訳語は「アーム」でよろしいかと存じます。
日本語の「腕」も、辞書を[みる](https://dictionary.goo.ne.jp/jn/19888/meaning/m0u/腕/)と、「道具などで、横に突き出た部位」と書いてありますが、パッと思いつく例が「腕木式信号機」ぐらいしかなく、あまり一般的ではない印象を受ける上、日本語で腕は比喩的にも用いられないという認識なので、腕と訳すのには抵抗があります。
ちなみに、辞書の用例にある「クレーンの腕」は「クレーンのアーム」と言ってしまいます。

こちらについてはいかがでしょうか？

**Comment by KeenS** [comment]
> こちらについてはいかがでしょうか？

そちらの議論を見落としてしました。こちらはアームで問題ないと思います。

**Comment by hazama-yuinyan** [comment]
承知しました。では、引き続きよろしくお願いいたします。
