### ISSUE TITLE
3章1節のマージについて

### ISSUE THREAD

**Issue by hazama-yuinyan** [hazama-yuinyan/book#13]
`to reason`の意味について、確認しておきたいことがあります。[英英辞典](https://www.ldoceonline.com/dictionary/reason)を確認したら、
> to form a particular judgment about a situation after carefully considering the facts(事実を注意深く考慮した後に、場面に関して特定の判断を形成すること)

とありましたので、「正しいことを確認する」というのは、名訳かなと思いますが、一応根拠を確かめさせていただきたいです。
@KeenSさんよろしくお願いいたします。

**Comment by KeenS** [comment]
同じく[oxford dictionary](https://en.oxforddictionaries.com/definition/reason)の

> Think, understand, and form judgements logically.

ですね。プログラムに対するものなので判断するのはプログラムの正しさかなと思い、そう訳しました。

**Comment by hazama-yuinyan** [comment]
なるほど、承知しました。では、それを採用しましょう。
