### ISSUE TITLE
rust-jp.rsサイトでのSecond Editionの公開について

### ISSUE THREAD

**Issue by tatsuya6502** [hazama-yuinyan/book#31]
こんにちは。私は[rust-lang-ja](https://github.com/rust-lang-ja)というGitHub Organizationで、@KeenSさんと共にRust文書の和訳に関わっている者です。

@hazama-yuinyanさんが翻訳されたSecond Editionが、upstream（rust-lang/book）にマージされることを心待ちにしているのですが、mdBookの多国語対応待ちとなっており、まだ時間がかかりそうですね。

せっかくの文書が使われないのはもったいないので、upstreamにマージされるまでは、私たちのサイト（[doc.rust-jp.rs](https://doc.rust-jp.rs)）で、rust-lang-jaで翻訳した他の文書と一緒にSecond Editionを公開させてもらいたいです。mdBookでビルドしたbookを以下のURLから読めるようにしました。

- https://doc.rust-jp.rs/book/second-edition/

ビルドはこちらのGitHubリポジトリからCircle CIを使って実現しています。

- https://github.com/rust-lang-ja/book
- https://circleci.com/gh/rust-lang-ja/book

ビルドは、いまのところ手動起動となっていますが、将来的には、定期的に起動（例：周1回）、または、hazama-yuinyan/bookにコミットがある毎に起動させたいと思っています。

なにかお気づきの点やご要望などあれば、お知らせください。

**Comment by hazama-yuinyan** [comment]
ご連絡ありがとうございます。bookは`mdbook`の仕様が変わる以前のものに依存していて、それが変更されてからも以前のバージョンを使わないと正しくレンダリングされない状態になってます。該当のissueを見る限り、`mdbook`の問題は根深そうなので、本家にマージされるのがいつになるか全く不透明な状態ですね。
ご連絡ありがとうございます。基本的に私の方でのコミットは原文も完成した今はもうない状態なので、PRをマージするくらいしか変更はありません。1回は通して精読したのですが、結構見落としがあるようで、ちらほらまだPRが来ています。

**Comment by tatsuya6502** [comment]
お返事ありがとうございました。マージなどの状況について承知しました。

ところで、`mdbook`ですが、bookのビルドにあたって、おすすめのバージョンはありますか？ いま私はbookのREADMEの説明を参考に、[0.1.7を使用しています](https://github.com/rust-lang-ja/circleci-images/blob/ba0f9a93d176cd025ccc404ed80afc982f5aff0c/docker/Dockerfile#L8)。

ちなみにこの`mdbook` 0.1.7ですが、SUMMARY.mdに連続した空行やHTMLコメントがあるとビルドが失敗するので、[ビルド直前にSUMMARY.mdからそれらを取り除いて](https://github.com/rust-lang-ja/book/blob/ebdc60c489005b761126005ffbda45a415799ff9/.circleci/config.yml#L24-L27)います。もし最新版の`mdbook`でもそうなるなら、時間のあるときに`mdbook`の方を直したいと考えています。

今後、あまりコミットはなさそうとのことですので、ビルドの自動起動は不要かもしれませんね。優先度を落とすことにします。

**Comment by hazama-yuinyan** [comment]
お返事ありがとうございます。私は確認したら、0.0.28を使用していました。これが仕様が変更される直前のバージョンだったのかもしれません。あるいは、単純に翻訳し始めた時のバージョンかもしれませんが、今主流のバージョンではレンダリングがおかしくなります。
0.0.28を使用していても、レンダリングがおかしな箇所はあって、気づいた部分はコメントで残すようにしているので、ご参考にしてください。

> ちなみにこのmdbook 0.1.7ですが、SUMMARY.mdに連続した空行やHTMLコメントがあるとビルドが失敗するので、

0.0.28では、この問題はなかったと思います。たまたま該当したことがないだけかもしれませんが。
まあでも、本家のREADME.mdに推奨のバージョンの記載があるのなら、そちらを使用するべきかもしれません。rust_upか何かを使用して両バージョンを試されてみてはいかがでしょうか？

**Comment by tatsuya6502** [comment]
`mdbook`のバージョン関連の情報、ありがとうございました。最新（0.2.x系）は使用しないようにします。mdファイル中のコメントも参考にします。

まだ全てのページに目を通したわけではないのですが、0.1.7のレンダリングは問題なさそうです。しばらくは0.1.7を使ってみて、もし不具合を見つけたら、0.0.28など他のバージョンも試そうと思います。
